sudo: required
services: 
  - docker
  
# build test images
before_install:
  - docker build -t pranavj1001/react-todo-client-test -f ./client/react-todo/dev.Dockerfile ./client/react-todo

# run tests
script:
  - docker run -e CI=true pranavj1001/react-todo-client-test npm test

after_success:
  # build production images
  - docker build -t pranavj1001/react-todo-client ./client/react-todo
  - docker build -t pranavj1001/react-todo-server ./server
  - docker build -t pranavj1001/react-todo-nginx ./nginx
  # Log in to DOCKER CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # push production images to docker hub
  - docker push pranavj1001/react-todo-client
  - docker push pranavj1001/react-todo-server
  - docker push pranavj1001/react-todo-nginx

deploy:
  provider: elasticbeanstalk
  region: ap-south-1
  app: react-todo
  env: ReactTodo-env
  bucket_name: elasticbeanstalk-ap-south-1-311143012582
  bucket_path: react-todo
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY