export const GET_TODO_LIST = 'GET_TODO_LIST';
export const SAVE_TODO = 'SAVE_TODO';
export const REMOVE_TODO = 'REMOVE_TODO';

export const RESET_BUCKET_STATE = 'RESET_BUCKET_STATE';
export const GET_BUCKET_LIST = 'GET_BUCKET_LIST';
export const GET_SINGLE_BUCKET = 'GET_SINGLE_BUCKET'
export const SAVE_BUCKET = 'SAVE_BUCKET';
export const REMOVE_BUCKET = 'REMOVE_BUCKET';
export const BUCKET_ID_CHANGED = 'BUCKET_ID_CHANGED';
export const BUCKET_TITLE_CHANGED = 'BUCKET_TITLE_CHANGED';
export const BUCKET_COLOR_CHANGED = 'BUCKET_COLOR_CHANGED';
export const BUCKET_VALIDATION_MESSAGE_CHANGED = 'BUCKET_VALIDATION_MESSAGE_CHANGED';